const places = {
  data: [
    {
      avgRating: 4.7,
      listingBathroomLabel: "1 bath",
      bathrooms: 1,
      listingBedLabel: "1 bed",
      bedrooms: 1,
      beds: 1,
      businessHostLabel: null,
      city: "Chicago",
      configurableContent: null,
      contextualPicturesPageInfo: {
        hasNextPage: true,
        endCursor: "NQ==",
      },
      emergencyMessage: null,
      listingFloatingMessage: null,
      formattedBadges: [],
      listingGuestLabel: "2 guests",
      id: "889682365540690201",
      isAutoTranslated: false,
      isNewListing: false,
      isSuperhost: false,
      relaxedFilterLabels: null,
      localizedCityName: "Chicago",
      localizedDistanceText: null,
      locationTitle: null,
      locationContext: null,
      listingName: "Cityscape Haven: Stylish Room in Chicago",
      listingObjType: "REPRESENTATIVE",
      neighborhood: null,
      listingPreviewAmenityNames: ["Wifi", "Air conditioning"],
      previewTags: [],
      publicAddress: "Chicago, IL, United States",
      reviews: [],
      reviewsCount: 229,
      richKickers: null,
      roomType: "Entire home/apt",
      roomTypeCategory: "entire_home",
      roomTypeId: null,
      spaceType: "Apartment",
      starRating: 4.5,
      summary: null,
      wishlistedCount: null,
      title: "Apartment in Chicago",
      avgRatingLocalized: "4.7 (229)",
      accessibilityLabel: "$114 per night",
      concatQualifierLeft: false,
      price: "$114",
      qualifier: "night",
      trailingContent: null,
      adults: 1,
      children: 0,
      infants: 0,
      checkin: "2023-08-06",
      checkout: "2023-08-11",
      relaxedAmenityIds: null,
      categoryTag: null,
      pets: 0,
      location: {
        mapBoundsHint: {
          northeast: {
            latitude: 42.13436,
            longitude: -87.62212999999997,
          },
          southwest: {
            latitude: 41.48618,
            longitude: -87.94812999999999,
          },
        },
        fallbackMapCenter: {
          latitude: 41.8781136,
          longitude: -87.6297982,
        },
      },
      verified: {
        enabled: false,
        badgeText: "Plus",
        badgeSecondaryText: "Verified",
        kickerBadgeType: "filled",
      },
      images: [
        "https://a0.muscache.com/im/pictures/prohost-api/Hosting-889682365540690201/original/ec584ab2-32c5-4b91-88f0-06bd637664f3.png?im_w=720",
        "https://a0.muscache.com/im/pictures/prohost-api/Hosting-889682365540690201/original/092a84c7-46bd-45a4-adc4-c61d3f10500f.png?im_w=720",
        "https://a0.muscache.com/im/pictures/prohost-api/Hosting-889682365540690201/original/893ed8dc-172c-4412-884a-1c78648187ce.png?im_w=720",
        "https://a0.muscache.com/im/pictures/prohost-api/Hosting-889682365540690201/original/c0ae260d-c771-4d39-ae65-70cc10a8f133.png?im_w=720",
        "https://a0.muscache.com/im/pictures/prohost-api/Hosting-889682365540690201/original/11bd7bb6-b907-4ae8-b3f5-8fbef1ccf7db.png?im_w=720",
        "https://a0.muscache.com/im/pictures/prohost-api/Hosting-889682365540690201/original/54fd5da6-3dd3-4eb2-bc02-351aafb5d323.png?im_w=720",
      ],
    },
    {
      avgRating: 5,
      listingBathroomLabel: "1 private bath",
      bathrooms: 1,
      listingBedLabel: "1 bed",
      bedrooms: 1,
      beds: 1,
      businessHostLabel: null,
      city: "New Lenox",
      configurableContent: null,
      contextualPicturesPageInfo: {
        hasNextPage: true,
        endCursor: "NQ==",
      },
      emergencyMessage: null,
      listingFloatingMessage: null,
      formattedBadges: [],
      listingGuestLabel: "2 guests",
      id: "52552179",
      isAutoTranslated: false,
      isNewListing: false,
      isSuperhost: false,
      relaxedFilterLabels: null,
      localizedCityName: "New Lenox",
      localizedDistanceText: null,
      locationTitle: null,
      locationContext: null,
      listingName: "A private room | Wi-fi | Kitchen| Washer | Dryer",
      listingObjType: "REGULAR",
      neighborhood: null,
      listingPreviewAmenityNames: [
        "Wifi",
        "Air conditioning",
        "Kitchen",
        "Self check-in",
      ],
      previewTags: [],
      publicAddress: "New Lenox, IL, United States",
      reviews: [],
      reviewsCount: 9,
      richKickers: null,
      roomType: "Private room",
      roomTypeCategory: "private_room",
      roomTypeId: null,
      spaceType: "Private room",
      starRating: 5,
      summary: null,
      wishlistedCount: null,
      title: "Place to stay in New Lenox",
      avgRatingLocalized: "5.0 (9)",
      accessibilityLabel: "$67 per night",
      concatQualifierLeft: false,
      price: "$67",
      qualifier: "night",
      trailingContent: null,
      adults: 1,
      children: 0,
      infants: 0,
      checkin: "2023-08-08",
      checkout: "2023-08-13",
      relaxedAmenityIds: null,
      categoryTag: null,
      pets: 0,
      location: {
        mapBoundsHint: {
          northeast: {
            latitude: 42.13436,
            longitude: -87.62212999999997,
          },
          southwest: {
            latitude: 41.48618,
            longitude: -87.94812999999999,
          },
        },
        fallbackMapCenter: {
          latitude: 41.8781136,
          longitude: -87.6297982,
        },
      },
      verified: {
        enabled: false,
        badgeText: "Plus",
        badgeSecondaryText: "Verified",
        kickerBadgeType: "filled",
      },
      images: [
        "https://a0.muscache.com/im/pictures/8fa6f8a5-ab57-4311-b4a7-a68ec55116de.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/64983751-8571-409b-beb9-65ec5a274378.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/377da2de-7213-4bb2-bae9-37fa29edf91d.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/miso/Hosting-52552179/original/0e7bb0a1-9b29-4d9c-ada3-03e6e74afcf3.jpeg?im_w=720",
        "https://a0.muscache.com/im/pictures/3c77e2d7-dd3f-433e-8751-28e70dc2988a.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/7c446855-cd6d-473e-9a01-a23ae49ccb81.jpg?im_w=720",
      ],
    },
    {
      avgRating: 4.33,
      listingBathroomLabel: "1 private bath",
      bathrooms: 1,
      listingBedLabel: "1 bed",
      bedrooms: 1,
      beds: 1,
      businessHostLabel: null,
      city: "Chicago",
      configurableContent: null,
      contextualPicturesPageInfo: {
        hasNextPage: true,
        endCursor: "NQ==",
      },
      emergencyMessage: null,
      listingFloatingMessage: null,
      formattedBadges: [],
      listingGuestLabel: "2 guests",
      id: "38351082",
      isAutoTranslated: false,
      isNewListing: false,
      isSuperhost: false,
      relaxedFilterLabels: null,
      localizedCityName: "Chicago",
      localizedDistanceText: null,
      locationTitle: null,
      locationContext: null,
      listingName: "Sleek - Claridge House, Standard King Room",
      listingObjType: "REPRESENTATIVE",
      neighborhood: null,
      listingPreviewAmenityNames: ["Wifi", "Air conditioning", "Self check-in"],
      previewTags: [],
      publicAddress: "Chicago, IL, United States",
      reviews: [],
      reviewsCount: 295,
      richKickers: null,
      roomType: "Private room",
      roomTypeCategory: "private_room",
      roomTypeId: null,
      spaceType: "Hotel room",
      starRating: 4.5,
      summary: null,
      wishlistedCount: null,
      title: "Boutique hotel in Chicago",
      avgRatingLocalized: "4.33 (295)",
      accessibilityLabel: "$166 per night",
      concatQualifierLeft: false,
      price: "$166",
      qualifier: "night",
      trailingContent: null,
      adults: 1,
      children: 0,
      infants: 0,
      checkin: "2023-08-05",
      checkout: "2023-08-10",
      relaxedAmenityIds: null,
      categoryTag: null,
      pets: 0,
      location: {
        mapBoundsHint: {
          northeast: {
            latitude: 42.13436,
            longitude: -87.62212999999997,
          },
          southwest: {
            latitude: 41.48618,
            longitude: -87.94812999999999,
          },
        },
        fallbackMapCenter: {
          latitude: 41.8781136,
          longitude: -87.6297982,
        },
      },
      verified: {
        enabled: false,
        badgeText: "Plus",
        badgeSecondaryText: "Verified",
        kickerBadgeType: "filled",
      },
      images: [
        "https://a0.muscache.com/im/pictures/ef9eb74e-7686-4778-943f-af551f2e4979.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/13ba6a0f-5392-44b6-94d6-3fc64c972434.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/48f19fe3-89dc-4a4b-9283-e26429ad54e4.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/a3449710-b3fd-417e-83f4-2128c1bbc379.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/1d9824ce-6ae3-4a78-bb92-c3e8fe4039e7.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/a139e2c7-bdd6-4f0a-b1ae-ad96572f7dd4.jpg?im_w=720",
      ],
    },
    {
      avgRating: null,
      listingBathroomLabel: "2 baths",
      bathrooms: 2,
      listingBedLabel: "1 bed",
      bedrooms: 1,
      beds: 1,
      businessHostLabel: null,
      city: "Chicago",
      configurableContent: null,
      contextualPicturesPageInfo: {
        hasNextPage: true,
        endCursor: "NQ==",
      },
      emergencyMessage: null,
      listingFloatingMessage: null,
      formattedBadges: [],
      listingGuestLabel: "1 guest",
      id: "941402552194609961",
      isAutoTranslated: false,
      isNewListing: true,
      isSuperhost: false,
      relaxedFilterLabels: null,
      localizedCityName: "Chicago",
      localizedDistanceText: null,
      locationTitle: null,
      locationContext: null,
      listingName: "Near Chinatown and Downtown",
      listingObjType: "REGULAR",
      neighborhood: null,
      listingPreviewAmenityNames: [
        "Wifi",
        "Air conditioning",
        "Kitchen",
        "Self check-in",
      ],
      previewTags: [],
      publicAddress: "Chicago, IL, United States",
      reviews: null,
      reviewsCount: 0,
      richKickers: null,
      roomType: "Private room",
      roomTypeCategory: "private_room",
      roomTypeId: null,
      spaceType: "Private room",
      starRating: null,
      summary: null,
      wishlistedCount: null,
      title: "Place to stay in Chicago",
      avgRatingLocalized: "New",
      accessibilityLabel: "$38 per night",
      concatQualifierLeft: false,
      price: "$38",
      qualifier: "night",
      trailingContent: null,
      adults: 1,
      children: 0,
      infants: 0,
      checkin: "2023-08-28",
      checkout: "2023-09-02",
      relaxedAmenityIds: null,
      categoryTag: null,
      pets: 0,
      location: {
        mapBoundsHint: {
          northeast: {
            latitude: 42.13436,
            longitude: -87.62212999999997,
          },
          southwest: {
            latitude: 41.48618,
            longitude: -87.94812999999999,
          },
        },
        fallbackMapCenter: {
          latitude: 41.8781136,
          longitude: -87.6297982,
        },
      },
      verified: {
        enabled: false,
        badgeText: "Plus",
        badgeSecondaryText: "Verified",
        kickerBadgeType: "filled",
      },
      images: [
        "https://a0.muscache.com/im/pictures/miso/Hosting-941402552194609961/original/37bc8480-cf60-47d1-a436-9f3c992f55ae.jpeg?im_w=720",
        "https://a0.muscache.com/im/pictures/c281a0e2-c4c8-4f96-a5bf-3ad9fb745913.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/d9c46913-3e1d-4687-8273-5441f01329c2.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/d1858b11-19d6-4d36-8582-4b4ab3bcc80e.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/f1c789cd-c744-4fdc-ab45-6987c9ef2b56.jpg?im_w=720",
        "https://a0.muscache.com/im/pictures/ffc21288-4801-47f1-95aa-b17eb6587a96.jpg?im_w=720",
      ],
    },
  ],
};


export const fetchPlaces = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(places);
    }, 2000)
})